### ISSUE TITLE
ffi.lua:42: Error: unable to locate HDF5 header file at hdf5.h

### ISSUE THREAD

**Issue by danieleewww** [deepmind/torch-hdf5#75]
traceback: Daniel-iMac:ultrasound-nerve-segmentation-using-torchnet py3$ th create_dataset.lua -train /Users/py3/torch/ultrasound-nerve-segmentation-using-torchnet/train/data/images -trainOutput /Users/py3/torch/ultrasound-nerve-segmentation-using-torchnet/train/data.h5 -test /Users/py3/torch/ultrasound-nerve-segmentation-using-torchnet/test/data -testOutput /Users/py3/torch/ultrasound-nerve-segmentation-using-torchnet/test/data.h5
/Users/py3/torch/install/bin/luajit: /Users/py3/torch/install/share/lua/5.1/trepl/init.lua:384: /Users/py3/torch/install/share/lua/5.1/hdf5/ffi.lua:42: Error: unable to locate HDF5 header file at hdf5.h
stack traceback:
	[C]: in function 'error'
	/Users/py3/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	create_dataset.lua:11: in main chunk
	[C]: in function 'dofile'
	.../py3/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010a49ad10
 
hdf5.h is actually located in  
/usr/local/Cellar/hdf5/1.8.16_1/include (using brew install hdf5)

Any suggestion for this!

**Comment by ruguevara** [comment]
I fixed this issue by installing cmake31 instead of 3.6 and reinstalling torch-hdf5

**Comment by danieleewww** [comment]
using "brew install cmake31" and "brew uninstall/reinstall hdf5" with "luarocks make hdf5-0-0.rockspec", but "ffi.lua:42: Error: unable to locate HDF5 header file at hdf5.h" issue remained; any suggestion for this!

**Comment by jjangsangy** [comment]
I was able to fix this issue by modifying the file `~/torch/install/share/lua/5.1/hdf5/config.lua`

And adding my include directory to the `HDF5_INCLUDE_PATH` like so.

```lua
    HDF5_INCLUDE_PATH = "/usr/local/include",
```

Hope this helps, wonder why the installation was not able to autodetect the hdf5 headers?

**Comment by danieleewww** [comment]
jjangsangy's suggestin fixed for this issue in my system.  (additional note: i had various hdf5.h's installed with anaconda for different project under local env. in the same system, it did not have this issue until torch/luarocks's in the global env.)

**Comment by kirk86** [comment]
@jjangsangy thanks, it saved the day.... 👍
